### ISSUE TITLE
Solution could not be found: Infeasible

### ISSUE THREAD

**Issue by LeagueLens** [dannybozbay/FPL-Optimization#1]
What does this mean?

`Traceback (most recent call last):
  File "/Users/josephpaturi/Documents/FPL/FPL-Optimization/RunOptimiser.py", line 534, in <module>
    opt.solve()
  File "/Users/josephpaturi/Documents/FPL/FPL-Optimization/RunOptimiser.py", line 293, in solve
    raise ValueError(f"Solution could not be found: {LpStatus[status]}")
ValueError: Solution could not be found: Infeasible`

**Comment by dbozbay** [comment]
Hi,

Sorry for the late response, I've been busy with another project.

As for the error, it usually arises because one of the following: 1) An incorrect `team_id` or `horizon` has been set inside the `src/settings.json` file or 2)  You have not downloaded the latest points projection file from FPLForm. 

Can you please provide me with your `team_id` and `horizon` settings so that I can debug the code myself over the weekend, and hopefully have it fixed for you by Sunday? :)

**Comment by LeagueLens** [comment]
did few tests and it cloud be due to duplicate names (Wood and Johnson

```
team_id : 156663
Horizon : 5
```

**Comment by dbozbay** [comment]
It scripts work fine on my end with your settings. The only causes for your error that I can think of are an outdated FPLForm file, or the settings.json file isn't formatted correctly. 

I've updated the package, so please follow the steps below carefully and let me know if the error persists:

1) Delete the package you downloaded last week and reclone the latest commit.

2) Follow the installation instructions. It's important that when you're downloading the latest projection file from FPLForm (step 3), you move the end slider to GW38 and select "With Extra Columns" before clicking "Generate CSV File".  

3) Ensure your `settings.json` file looks exactly like this before  saving it and running the `run_optimiser.py` script.

    ```sh
    {
      "team_id": 156663,
      "horizon": 5
    }
    ```

**Comment by LeagueLens** [comment]
i pulled the latest copy and it worked today!

**Comment by dbozbay** [comment]
Awesome. Good luck with your FPL!
